import Head from "next/head";
import { useCallback, useMemo, useState } from "react";
import Footer from "scenes/home/Footer";
import OrderDialog from "scenes/home/order_dialog";
import PaginateSlider from "components/pagination";
import Test from "scenes/home/test";
import PrimaryButton_2 from "components/primary_button_test";
import AboutBrand from "scenes/home/about_brand";
import Header from "scenes/home/header";

export default function Home() {
  const [showDialog, setShowDialog] = useState(false);
  const [dot, setDot] = useState(0);

  //HandleShowDialog
  const handleShowDialog = useCallback(() => {
    setShowDialog(!showDialog);
  }, [showDialog])

  const ORDER_DIALOG = useMemo(() => {
    if (showDialog)
      return <OrderDialog closeDiaLog={handleShowDialog} />;
  }, [showDialog])

  return (
    <div>
      <Head>
        <title>DAX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Footer /> */}
      <Header />


      <div className="flex justify-center items-center">
        <button
          type='button'
          className="bg-green-300 p-2 rounded-md hover:bg-slate-600 hover:text-white hover:scale-125 transition"
          onClick={handleShowDialog}>Show Dialog
        </button>
      </div>
      {ORDER_DIALOG}

      <AboutBrand />
    </div>
  );
}
