import Head from "next/head";
import { useState } from "react";
import OrderDialog from "../scenes/home/order_dialog";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [showDialog, setShowDialog] = useState(false);
  const handleShowModal = () => {
    setShowDialog(!showDialog);
  }
  return (
    <div>
      <Head>
        <title>DAX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="flex justify-center items-center">
        <button
          type='button'
          className="bg-green-300 p-2 rounded-md hover:bg-slate-600 hover:text-white hover:scale-125 transition"
          onClick={handleShowModal}>Show Dialog
        </button>
      </div>
      {showDialog ? <OrderDialog closeDiaLog={handleShowModal} /> : null}
    </div>
  );
}
