import Head from "next/head";
import { useCallback, useMemo, useState } from "react";
import Footer from "scenes/home/Footer";
import OrderDialog from "scenes/home/order_dialog";
import Header from "scenes/home/header";
import AboutArtist from "scenes/home/AboutArtist";
import styles from "styles/Home.module.css"


export default function Home() {
  const [showDialog, setShowDialog] = useState(false);
  const handleShowDialog = useCallback(() => {
    setShowDialog(!showDialog);
  }, [showDialog])

  const orderDialog = useMemo(() => {
    if (showDialog)
      return <OrderDialog closeDiaLog={handleShowDialog} />;
  }, [showDialog])


  return (
    <div className={`containerApp ${styles.containerApp}`}>
      <Head>
        <title>DAX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header className="xl:min-h-screen snap-start "/>
     
      <AboutArtist />
      <Footer />

    
{/* 
      <div className="flex justify-center items-center">
        <button
          type='button'
          className="bg-green-300 p-2 rounded-md hover:bg-slate-600 hover:text-white hover:scale-125 transition"
          onClick={handleShowDialog}>Show Dialog
        </button>
      </div>
      {orderDialog} */}
    </div>
  );
}
